name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all git history
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        check-latest: true
    - name: Set up Cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: make all
    - name: Report Test Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt
