name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    - name: Set up Cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: build binaries
      run: make release
    - name: populate release
      uses: softprops/action-gh-release@v1
      with:
        files: irel-*-amd64*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
